## Instructions

#### 。 This homework has two parts
    1. There are 6 simple questions, just follow the instrctions and get the same output as the following.
    2. It's how simple neural networks work. As the same as part 1, just follow the instructions and get the same output

#### 。 All of this homework should use Numpy or Pandas

#### 。 Please follow the same variable name as the instuctions of every questions 

## Part 1

**1. Import both numpy and pandas packages**

In [2]:
import numpy as np
import pandas as pd

**2. Create a 3x3 matrix with values ranging from 0 to 8**

In [3]:
array = np.array([range(0, 3), range(3, 6), range(6, 9)])
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**3. Create a 5x5 matrix with row values ranging from 0 to 4**

In [4]:
array = np.tile(range(0, 5), (5, 1))
array

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

**4. How to swap the first and second rows of a**

In [5]:
a = np.arange(25).reshape(5,5)
a[[0, 1]] = a[[1, 0]]
a

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**5. Give two ways to show how to get the n largest values of a (no sort the value is fine)**

In [6]:
# Don't need to change this cell
a = np.arange(100)
np.random.shuffle(a)
n = 5

In [7]:
# Way 1

a_sorted = np.sort(a)
a_sorted[-n:]

array([95, 96, 97, 98, 99])

In [8]:
# Way 2

indices = np.argpartition(a, -n)[-n:]
a[indices]

array([95, 96, 97, 98, 99])

**6. Compare if array a and array b is totally the same**

In [9]:
np.random.seed(123)
a = np.round(np.random.random(100)*100, 0)
b = np.random.randint(1, 100, 100)

# Put your code here
if (np.array_equal(a, b)):
    print('Arrays are equal')

## Part 2

### Online Shoppers Purchasing Intention Dataset

The dataset consists of 10 numerical and 8 categorical attributes. The 'Revenue' attribute can be used as the class label.

* ``0 Administrative``, ``1 Administrative Duration``, ``2 Informational``, ``3 Informational Duration``, ``4 Product Related`` and ``5 Product Related Duration`` - represent the number of different types of pages visited by the visitor in that session and total time spent in each of these page categories. The values of these features are derived from the URL information of the pages visited by the user and updated in real time when a user takes an action, e.g. moving from one page to another. 


* ``6 Bounce Rate``, ``7 Exit Rate`` and ``8 Page Value`` - represent the metrics measured by "Google Analytics" for each page in the e-commerce site. The value of "Bounce Rate" feature for a web page refers to the percentage of visitors who enter the site from that page and then leave ("bounce") without triggering any other requests to the analytics server during that session. The value of "Exit Rate" feature for a specific web page is calculated as for all pageviews to the page, the percentage that were the last in the session. The "Page Value" feature represents the average value for a web page that a user visited before completing an e-commerce transaction. 


* ``9 Special Day`` - indicates the closeness of the site visiting time to a specific special day (e.g. Mother’s Day, Valentine's Day) in which the sessions are more likely to be finalized with transaction. The value of this attribute is determined by considering the dynamics of e-commerce such as the duration between the order date and delivery date. For example, for Valentina’s day, this value takes a nonzero value between February 2 and February 12, zero before and after this date unless it is close to another special day, and its maximum value of 1 on February 8. 


* The dataset also includes ``11 operating system``, ``12 browser``, ``13 region``, ``14 traffic type``, ``15 visitor type`` as returning or new visitor, a Boolean value indicating whether the date of the visit is ``16 weekend``, and ``9 month of the year``.


---
* **``17 Revenue``** - binary labels



* More information of this data: [UCI | Online Shoppers Purchasing Intention Dataset](https://archive.ics.uci.edu/ml/datasets/Online+Shoppers+Purchasing+Intention+Dataset#)

**Use pandas to import the data and check the shape of dataset and save it as `" shoppers "`**

In [10]:
shoppers = pd.read_csv('online_shoppers_intention.csv')
shape = shoppers.shape
shape

(12330, 18)

**Use pandas function to let label be numeric as below and save it as `" label "`**

In [16]:
label = pd.Series(shoppers['Revenue']).array
# change the type of label to int array
label = label.astype(int)
label

array([0, 0, 0, ..., 0, 0, 0])

**See some information of this data**

In [17]:
from tabulate import tabulate
print(tabulate(shoppers))

-----  --  ----------  --  ----------  ---  -----------  -----------  -----------  -----------  ---  ----  -  --  -  --  -----------------  -----  -----
    0   0     0         0     0          1      0        0.2          0.2            0          0    Feb   1   1  1   1  Returning_Visitor  False  False
    1   0     0         0     0          2     64        0            0.1            0          0    Feb   2   2  1   2  Returning_Visitor  False  False
    2   0     0         0     0          1      0        0.2          0.2            0          0    Feb   4   1  9   3  Returning_Visitor  False  False
    3   0     0         0     0          2      2.66667  0.05         0.14           0          0    Feb   3   2  2   4  Returning_Visitor  False  False
    4   0     0         0     0         10    627.5      0.02         0.05           0          0    Feb   3   3  1   4  Returning_Visitor  True   False
    5   0     0         0     0         19    154.217    0.0157895    0.0245614   

In [18]:
print(tabulate(shoppers.head(10), headers='keys', tablefmt='psql'))

+----+------------------+---------------------------+-----------------+--------------------------+------------------+---------------------------+---------------+-------------+--------------+--------------+---------+--------------------+-----------+----------+---------------+-------------------+-----------+-----------+
|    |   Administrative |   Administrative_Duration |   Informational |   Informational_Duration |   ProductRelated |   ProductRelated_Duration |   BounceRates |   ExitRates |   PageValues |   SpecialDay | Month   |   OperatingSystems |   Browser |   Region |   TrafficType | VisitorType       | Weekend   | Revenue   |
|----+------------------+---------------------------+-----------------+--------------------------+------------------+---------------------------+---------------+-------------+--------------+--------------+---------+--------------------+-----------+----------+---------------+-------------------+-----------+-----------|
|  0 |                0 |               

**Choose column [1, 4, 5, 11, 12, 13] and turn into numpy array ``" x "``**

In [19]:
x = shoppers.iloc[:, [1, 4, 5, 11, 12, 13]].to_numpy()

In [20]:
x

array([[  0.  ,   1.  ,   0.  ,   1.  ,   1.  ,   1.  ],
       [  0.  ,   2.  ,  64.  ,   2.  ,   2.  ,   1.  ],
       [  0.  ,   1.  ,   0.  ,   4.  ,   1.  ,   9.  ],
       ...,
       [  0.  ,   6.  , 184.25,   3.  ,   2.  ,   1.  ],
       [ 75.  ,  15.  , 346.  ,   2.  ,   2.  ,   3.  ],
       [  0.  ,   3.  ,  21.25,   3.  ,   2.  ,   1.  ]])

**Use numpy function to load weight data, bias data and check their shape**

In [21]:
weight_1 = np.load('layer_1_weight.npy')
weight_2 = np.load('layer_2_weight.npy')

bias_1 = np.load('layer_1_bias.npy')
bias_2 = np.load('layer_2_bias.npy')

In [22]:
print('weight_1 shape:', weight_1.shape)
print('weight_2 shape:', weight_2.shape)
print('')
print('bias_1 shape:', bias_1.shape)
print('bias_2 shape:', bias_2.shape)

weight_1 shape: (6, 32)
weight_2 shape: (32, 2)

bias_1 shape: (32,)
bias_2 shape: (2,)


**Use numpy function to compute `" x "` and weight_1 matrix multiplication, and check the shape**

In [23]:
x = x @ weight_1
x.shape

(12330, 32)

**Use numpy function to compute `" x "` and bias_1 matrix addtion, and check the shape**

In [24]:
x = x + bias_1
x.shape

(12330, 32)

**Use numpy function to compute `" x "` and weight_2 matrix multiplication, and check the shape**

In [25]:
x = x @ weight_2
x.shape

(12330, 2)

**Use numpy function to compute `" x "` and bias_2 matrix addtion, and check the shape**

In [26]:
x = x + bias_2
x.shape

(12330, 2)

**Check if your x is same as below**

In [27]:
x

array([[ -0.42815397,  -0.58708018],
       [ 17.76804854, -12.0093477 ],
       [ -1.07327452,  -3.72237766],
       ...,
       [ 51.70654464, -34.08445513],
       [110.52965928, -73.95802223],
       [  5.45892153,  -4.42243782]])

**Use numpy function to find out each row which one value is bigger, and save it as `" pre "`**

In [28]:
pre = np.argmax(x, axis=1)
pre

array([0, 0, 0, ..., 0, 0, 0])

**Use numpy function to check if `pre[i]` is the same as `label[i]`, and save it as `" check "`**

In [29]:
check = np.equal(pre, label)
check

array([ True,  True,  True, ...,  True,  True,  True])

**Use numpy function to calculate the accuracy**

In [30]:
print('accuracy:', np.mean(check))

accuracy: 0.8284671532846716
